"""add dryness column

Revision ID: 5cd38de5712f
Revises: c1f2a3b4c5d6
Create Date: 2026-01-29 14:02:50.890979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cd38de5712f'
down_revision: Union[str, None] = 'c1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('condition_logs', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('condition_logs', sa.Column('dryness', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('condition_logs', 'dryness')
    op.drop_column('condition_logs', 'city')
    # ### end Alembic commands ###
