"""remove period_end_date from condition_logs

Revision ID: a9523b88e954
Revises: 0c5aaf492ee3
Create Date: 2026-01-29 12:31:22.241612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9523b88e954'
down_revision: Union[str, None] = '0c5aaf492ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('condition_logs', 'period_end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('condition_logs', sa.Column('period_end_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
